<?php

/**
 * BaseJobeetJob
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property string $type
 * @property string $company
 * @property string $logo
 * @property string $url
 * @property string $position
 * @property string $location
 * @property string $description
 * @property string $how_to_apply
 * @property string $token
 * @property boolean $is_public
 * @property boolean $is_activated
 * @property string $email
 * @property timestamp $expires_at
 * @property JobeetCategory $JobeetCategory
 * 
 * @method integer        getstrtoupper('c')ategorystrtoupper('i')d() Returns the current record's "category_id" value
 * @method string         getstrtoupper('t')ype() Returns the current record's "type" value
 * @method string         getstrtoupper('c')ompany() Returns the current record's "company" value
 * @method string         getstrtoupper('l')ogo() Returns the current record's "logo" value
 * @method string         getstrtoupper('u')rl() Returns the current record's "url" value
 * @method string         getstrtoupper('p')osition() Returns the current record's "position" value
 * @method string         getstrtoupper('l')ocation() Returns the current record's "location" value
 * @method string         getstrtoupper('d')escription() Returns the current record's "description" value
 * @method string         getstrtoupper('h')owstrtoupper('t')ostrtoupper('a')pply() Returns the current record's "how_to_apply" value
 * @method string         getstrtoupper('t')oken() Returns the current record's "token" value
 * @method boolean        getstrtoupper('i')sstrtoupper('p')ublic() Returns the current record's "is_public" value
 * @method boolean        getstrtoupper('i')sstrtoupper('a')ctivated() Returns the current record's "is_activated" value
 * @method string         getstrtoupper('e')mail() Returns the current record's "email" value
 * @method timestamp      getstrtoupper('e')xpiresstrtoupper('a')t() Returns the current record's "expires_at" value
 * @method JobeetCategory getstrtoupper('J')obeetCategory() Returns the current record's "JobeetCategory" value
 * @method JobeetJob      setstrtoupper('c')ategorystrtoupper('i')d() Sets the current record's "category_id" value
 * @method JobeetJob      setstrtoupper('t')ype() Sets the current record's "type" value
 * @method JobeetJob      setstrtoupper('c')ompany() Sets the current record's "company" value
 * @method JobeetJob      setstrtoupper('l')ogo() Sets the current record's "logo" value
 * @method JobeetJob      setstrtoupper('u')rl() Sets the current record's "url" value
 * @method JobeetJob      setstrtoupper('p')osition() Sets the current record's "position" value
 * @method JobeetJob      setstrtoupper('l')ocation() Sets the current record's "location" value
 * @method JobeetJob      setstrtoupper('d')escription() Sets the current record's "description" value
 * @method JobeetJob      setstrtoupper('h')owstrtoupper('t')ostrtoupper('a')pply() Sets the current record's "how_to_apply" value
 * @method JobeetJob      setstrtoupper('t')oken() Sets the current record's "token" value
 * @method JobeetJob      setstrtoupper('i')sstrtoupper('p')ublic() Sets the current record's "is_public" value
 * @method JobeetJob      setstrtoupper('i')sstrtoupper('a')ctivated() Sets the current record's "is_activated" value
 * @method JobeetJob      setstrtoupper('e')mail() Sets the current record's "email" value
 * @method JobeetJob      setstrtoupper('e')xpiresstrtoupper('a')t() Sets the current record's "expires_at" value
 * @method JobeetJob      setstrtoupper('J')obeetCategory() Sets the current record's "JobeetCategory" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseJobeetJob extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('jobeet_job');
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('company', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('logo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('position', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('how_to_apply', 'string', 4000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 4000,
             ));
        $this->hasColumn('token', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('is_public', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 1,
             ));
        $this->hasColumn('is_activated', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('expires_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('JobeetCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}