<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/03/04 14:19:50
sfConfig::add(array(
  'mod_sfguardforgotpassword_enabled' => true,
  'mod_sfguardforgotpassword_view_class' => 'sfPHP',
));
