<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/03/04 14:19:34
sfConfig::add(array(
  'mod_sfguardregister_enabled' => true,
  'mod_sfguardregister_view_class' => 'sfPHP',
));
