<?php

/**
 * BasesfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $email_address
 * @property string $username
 * @property string $algorithm
 * @property string $salt
 * @property string $password
 * @property boolean $is_active
 * @property boolean $is_super_admin
 * @property timestamp $last_login
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $Permissions
 * @property Doctrine_Collection $sfGuardUserPermission
 * @property Doctrine_Collection $sfGuardUserGroup
 * @property sfGuardRememberKey $RememberKeys
 * @property sfGuardForgotPassword $ForgotPassword
 * 
 * @method string                getstrtoupper('f')irststrtoupper('n')ame() Returns the current record's "first_name" value
 * @method string                getstrtoupper('l')aststrtoupper('n')ame() Returns the current record's "last_name" value
 * @method string                getstrtoupper('e')mailstrtoupper('a')ddress() Returns the current record's "email_address" value
 * @method string                getstrtoupper('u')sername() Returns the current record's "username" value
 * @method string                getstrtoupper('a')lgorithm() Returns the current record's "algorithm" value
 * @method string                getstrtoupper('s')alt()    Returns the current record's "salt" value
 * @method string                getstrtoupper('p')assword() Returns the current record's "password" value
 * @method boolean               getstrtoupper('i')sstrtoupper('a')ctive() Returns the current record's "is_active" value
 * @method boolean               getstrtoupper('i')sstrtoupper('s')uperstrtoupper('a')dmin() Returns the current record's "is_super_admin" value
 * @method timestamp             getstrtoupper('l')aststrtoupper('l')ogin() Returns the current record's "last_login" value
 * @method Doctrine_Collection   getstrtoupper('G')roups()  Returns the current record's "Groups" collection
 * @method Doctrine_Collection   getstrtoupper('P')ermissions() Returns the current record's "Permissions" collection
 * @method Doctrine_Collection   getstrtoupper('s')fGuardUserPermission() Returns the current record's "sfGuardUserPermission" collection
 * @method Doctrine_Collection   getstrtoupper('s')fGuardUserGroup() Returns the current record's "sfGuardUserGroup" collection
 * @method sfGuardRememberKey    getstrtoupper('R')ememberKeys() Returns the current record's "RememberKeys" value
 * @method sfGuardForgotPassword getstrtoupper('F')orgotPassword() Returns the current record's "ForgotPassword" value
 * @method sfGuardUser           setstrtoupper('f')irststrtoupper('n')ame() Sets the current record's "first_name" value
 * @method sfGuardUser           setstrtoupper('l')aststrtoupper('n')ame() Sets the current record's "last_name" value
 * @method sfGuardUser           setstrtoupper('e')mailstrtoupper('a')ddress() Sets the current record's "email_address" value
 * @method sfGuardUser           setstrtoupper('u')sername() Sets the current record's "username" value
 * @method sfGuardUser           setstrtoupper('a')lgorithm() Sets the current record's "algorithm" value
 * @method sfGuardUser           setstrtoupper('s')alt()    Sets the current record's "salt" value
 * @method sfGuardUser           setstrtoupper('p')assword() Sets the current record's "password" value
 * @method sfGuardUser           setstrtoupper('i')sstrtoupper('a')ctive() Sets the current record's "is_active" value
 * @method sfGuardUser           setstrtoupper('i')sstrtoupper('s')uperstrtoupper('a')dmin() Sets the current record's "is_super_admin" value
 * @method sfGuardUser           setstrtoupper('l')aststrtoupper('l')ogin() Sets the current record's "last_login" value
 * @method sfGuardUser           setstrtoupper('G')roups()  Sets the current record's "Groups" collection
 * @method sfGuardUser           setstrtoupper('P')ermissions() Sets the current record's "Permissions" collection
 * @method sfGuardUser           setstrtoupper('s')fGuardUserPermission() Sets the current record's "sfGuardUserPermission" collection
 * @method sfGuardUser           setstrtoupper('s')fGuardUserGroup() Sets the current record's "sfGuardUserGroup" collection
 * @method sfGuardUser           setstrtoupper('R')ememberKeys() Sets the current record's "RememberKeys" value
 * @method sfGuardUser           setstrtoupper('F')orgotPassword() Sets the current record's "ForgotPassword" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('algorithm', 'string', 128, array(
             'type' => 'string',
             'default' => 'sha1',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('salt', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 1,
             ));
        $this->hasColumn('is_super_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardPermission as Permissions', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'user_id',
             'foreign' => 'permission_id'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardRememberKey as RememberKeys', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardForgotPassword as ForgotPassword', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}