<?php

/**
 * BasesfGuardUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $group_id
 * @property sfGuardUser $User
 * @property sfGuardGroup $Group
 * 
 * @method integer          getstrtoupper('u')serstrtoupper('i')d() Returns the current record's "user_id" value
 * @method integer          getstrtoupper('g')roupstrtoupper('i')d() Returns the current record's "group_id" value
 * @method sfGuardUser      getstrtoupper('U')ser() Returns the current record's "User" value
 * @method sfGuardGroup     getstrtoupper('G')roup() Returns the current record's "Group" value
 * @method sfGuardUserGroup setstrtoupper('u')serstrtoupper('i')d() Sets the current record's "user_id" value
 * @method sfGuardUserGroup setstrtoupper('g')roupstrtoupper('i')d() Sets the current record's "group_id" value
 * @method sfGuardUserGroup setstrtoupper('U')ser() Sets the current record's "User" value
 * @method sfGuardUserGroup setstrtoupper('G')roup() Sets the current record's "Group" value
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUserGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_group');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('sfGuardGroup as Group', array(
             'local' => 'group_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}