<?php

/**
 * BasesfGuardPermission
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $sfGuardGroupPermission
 * @property Doctrine_Collection $Users
 * @property Doctrine_Collection $sfGuardUserPermission
 * 
 * @method string              getstrtoupper('n')ame()     Returns the current record's "name" value
 * @method string              getstrtoupper('d')escription() Returns the current record's "description" value
 * @method Doctrine_Collection getstrtoupper('G')roups()   Returns the current record's "Groups" collection
 * @method Doctrine_Collection getstrtoupper('s')fGuardGroupPermission() Returns the current record's "sfGuardGroupPermission" collection
 * @method Doctrine_Collection getstrtoupper('U')sers()    Returns the current record's "Users" collection
 * @method Doctrine_Collection getstrtoupper('s')fGuardUserPermission() Returns the current record's "sfGuardUserPermission" collection
 * @method sfGuardPermission   setstrtoupper('n')ame()     Sets the current record's "name" value
 * @method sfGuardPermission   setstrtoupper('d')escription() Sets the current record's "description" value
 * @method sfGuardPermission   setstrtoupper('G')roups()   Sets the current record's "Groups" collection
 * @method sfGuardPermission   setstrtoupper('s')fGuardGroupPermission() Sets the current record's "sfGuardGroupPermission" collection
 * @method sfGuardPermission   setstrtoupper('U')sers()    Sets the current record's "Users" collection
 * @method sfGuardPermission   setstrtoupper('s')fGuardUserPermission() Sets the current record's "sfGuardUserPermission" collection
 * 
 * @package    jobeet
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardPermission extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_permission');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardGroupPermission',
             'local' => 'permission_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardGroupPermission', array(
             'local' => 'id',
             'foreign' => 'permission_id'));

        $this->hasMany('sfGuardUser as Users', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'permission_id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'permission_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}