<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/03/03 21:04:40
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
