<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/03/06 22:30:51
sfConfig::add(array(
  'mod_sfjobeetlanguage_enabled' => true,
  'mod_sfjobeetlanguage_view_class' => 'sfPHP',
));
