<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/03/06 22:59:15
sfConfig::add(array(
  'mod_sfjobeetaffiliate_enabled' => true,
  'mod_sfjobeetaffiliate_view_class' => 'sfPHP',
));
