<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/03/06 12:50:38
sfConfig::add(array(
  'mod_sfjobeetcategory_enabled' => true,
  'mod_sfjobeetcategory_view_class' => 'sfPHP',
));
