<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/03/05 21:58:15
sfConfig::add(array(
  'mod_sfjobeetlanguage_enabled' => true,
  'mod_sfjobeetlanguage_view_class' => 'sfPHP',
));
