<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/03/05 22:34:21
sfConfig::add(array(
  'mod_sfjobeetcategory_enabled' => true,
  'mod_sfjobeetcategory_view_class' => 'sfPHP',
));
