<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/03/05 22:44:48
sfConfig::add(array(
  'mod_sfjobeetaffiliate_enabled' => true,
  'mod_sfjobeetaffiliate_view_class' => 'sfPHP',
));
